const API_CODES:  {
  // base codes
  SUCCESS: 0,
  FAILURE: 1000,

  // auth codes
  ERROR_REGISTER_USER: 1001,
  ERROR_EMPTY_CREDENTIALS: 1002,
  ERROR_INVALID_CREDENTIALS: 1003,
  ERROR_VERIFY_XSRF_TOKEN: 1004,
  ERROR_PAYLOAD: 1005,
  ERROR_PAYLOAD_USER: 1006,
  ERROR_AUTH_MIDDLEEARE_TOKEN: 1007,
  ERROR_AUTH_MIDDLEEARE_EMPTY_XSRF_TOKEN: 1008,
  ERROR_AUTH_MIDDLEEARE_UNMATCHED_XSRF_TOKEN: 1009,
  ERROR_AUTH_MIDDLEEARE_UNVERIFIED_XSRF_TOKEN: 1010,
  ERROR_EMAIL_EXISTS: 1011,
}

module.exports = API_CODES;