const ERRORS = {};
ERRORS.AUTH = {
    REGISTER: 100,
    REGISTER_VALIDATION: 101,
    REGISTER_EMAIL_EXISTS: 102,
    LOGIN: 200,
    LOGIN_EMPTY_CREDENTIALS: 201,
    LOGIN_INVALID_CREDENTIALS: 202,
    LOGOUT: 300,
    VERIFY: 400,
    VERIFY_UNSIGNED_TOKEN: 401,
    VERIFY_INVALID_USER: 402,
};
    // auth/register

ERRORS.LOGIN = {
    EMPTY_CREDENTIALS: 111111,
    INVALID_CREDENTIALS: 1003,
    JWT_UNAUTHORIZED: 1004,
    UNSIGNED_TOKEN: 1005,
    INVALID_TOKEN: 1006,
    EMAIL_EXISTS: 1005,

    // admin api
    ADMIN_GET_ROOMS_FAILURE: 1100,
    ADMIN_SAVING_ROOMS_FAILURE: 1101,
    ADMIN_SAVING_ROOMS_DUPLICATE: 1102,
    ADMIN_SAVING_ROOMS_INPUT: 1103,
    ADMIN_DELETING_ROOMS: 1104,
    ADMIN_ROOM_NOT_EXISTS: 1105,

    // SCHEDULE api
    SCHEDULE_GET_LIST_ROOM: 1200,

    // Room api
    ROOM_FAILURE: 13000,
}
module.exports.ERRORS = ERRORS;
module.exports.SUCCESS = 0;
module.exports.FAILURE = 1;
